name: build test

on:  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CONFIGURATION: Release

jobs:
  build-test:    
    runs-on: ubuntu-latest    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101    
    - name: Restore dependencies
      run: dotnet restore GitHubPackageDemo.sln    
    - name: Build
      run: dotnet build GitHubPackageDemo.sln --configuration {{env.CONFIGURATION}} --no-restore    
    - name: Test
      run: dotnet test GitHubPackageDemo.sln --configuration {{env.CONFIGURATION}}